services:

  postgres:
    image: docker.io/library/postgres:16.4-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  
  backstage:
    image: backstage
    container_name: "backstage"
    depends_on:
      - postgres
    ports:
      - 7007:7007
    environment:
      - BACKSTAGE_BASE_URL=http://localhost:7007
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - GITHUB_TOKEN
      - AUTH_GITHUB_CLIENT_ID
      - AUTH_GITHUB_CLIENT_SECRET
