version: "3.8"
services:

  postgres:
    image: postgres:16.2-alpine
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  
  backstage:
    image: backstage
    container_name: "backstage"
    ports:
      - 7007:7007
    environment:
      - BACKSTAGE_BASE_URL=http://localhost:7007
      - BACKSTAGE_BACKEND_SECRET=lYXoL2XuDhIJE07CMTOunVB0pdZNCgS2
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - GITHUB_TOKEN
      - GITHUB_AUTH_PROVIDER_CLIENT_ID
      - GITHUB_AUTH_PROVIDER_CLIENT_SECRET
