---
apiVersion: app.kadras.io/v1alpha1
kind: Workload
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
spec:
  image: ghcr.io/${{ values.repoUrl.owner | lower }}/${{ values.repoUrl.repo }}
  application:
    framework: spring-boot
    language: java
  serviceClaims:
    {%- if values.llmProvider == "mistral" %}
    - name: mistral-ai
    {%- endif %}
    {%- if values.llmProvider == "ollama" %}
    - name: ollama
    {%- endif %}
    {%- if values.vectorStore == "postgresql" %}
    - name: postgresql
    {%- endif %}
