---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kadras
  title: Kadras
  description: Researching technology to power your path from idea to production on Kubernetes.
  links:
    - url: https://www.kadras.io
      title: Website
    - url: https://github.com/kadras-io
      title: GitHub
      icon: github
    - url: https://bsky.app/profile/kadras.io
      title: Bluesky
      icon: bluesky
spec:
  type: organization
  profile:
    displayName: Kadras
    picture: https://avatars.githubusercontent.com/u/122495299?s=400&u=b7253f864937e362b42c0b390da51ea9492194f4&v=4
  children: []
